"""Dependency-free PEP 660 backend for the deliberately minimal project."""

from __future__ import annotations

import base64
import csv
from hashlib import sha256
import io
from pathlib import Path
import zipfile

NAME = "modembench"
VERSION = "0.1.0"
DIST_INFO = f"{NAME}-{VERSION}.dist-info"
WHEEL_NAME = f"{NAME}-{VERSION}-py3-none-any.whl"

METADATA = f"""Metadata-Version: 2.4
Name: {NAME}
Version: {VERSION}
Summary: Deterministic signal-recovery benchmark spine
Requires-Python: >=3.14,<3.15
Requires-Dist: numpy==2.5.1
Requires-Dist: scipy==1.18.0
Requires-Dist: pytest==9.1.1
"""
WHEEL = """Wheel-Version: 1.0
Generator: modembench-local-backend
Root-Is-Purelib: true
Tag: py3-none-any
"""
ENTRY_POINTS = """[console_scripts]
modembench = modembench.cli:main
"""


def get_requires_for_build_editable(config_settings=None):
    return []


def get_requires_for_build_wheel(config_settings=None):
    return []


def prepare_metadata_for_build_editable(metadata_directory, config_settings=None):
    target = Path(metadata_directory) / DIST_INFO
    target.mkdir(parents=True, exist_ok=True)
    (target / "METADATA").write_text(METADATA, encoding="utf-8")
    (target / "WHEEL").write_text(WHEEL, encoding="utf-8")
    (target / "entry_points.txt").write_text(ENTRY_POINTS, encoding="utf-8")
    return DIST_INFO


def _record_row(path: str, content: bytes) -> tuple[str, str, str]:
    digest = base64.urlsafe_b64encode(sha256(content).digest()).rstrip(b"=").decode("ascii")
    return path, f"sha256={digest}", str(len(content))


def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
    source_package = Path(__file__).resolve().parent / "src" / NAME
    src = source_package.parent.as_posix().encode("utf-8") + b"\n"
    # Python 3.14 ignores .pth files carrying macOS's UF_HIDDEN flag, which cloud-backed
    # workspaces can reapply, so also install a real package stub.
    editable_stub = f'''"""Editable loader generated by modembench's local backend."""
from pathlib import Path as _Path
__path__ = [{str(source_package)!r}]
_source_init = _Path(__path__[0]) / "__init__.py"
exec(compile(_source_init.read_bytes(), str(_source_init), "exec"), globals())
'''.encode("utf-8")
    contents = {
        f"{NAME}_editable.pth": src,
        f"{NAME}/__init__.py": editable_stub,
        f"{DIST_INFO}/METADATA": METADATA.encode("utf-8"),
        f"{DIST_INFO}/WHEEL": WHEEL.encode("utf-8"),
        f"{DIST_INFO}/entry_points.txt": ENTRY_POINTS.encode("utf-8"),
    }
    record_path = f"{DIST_INFO}/RECORD"
    rows = [_record_row(path, content) for path, content in contents.items()]
    rows.append((record_path, "", ""))
    record = io.StringIO(newline="")
    csv.writer(record, lineterminator="\n").writerows(rows)
    contents[record_path] = record.getvalue().encode("utf-8")

    destination = Path(wheel_directory) / WHEEL_NAME
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path, content in contents.items():
            archive.writestr(path, content)
    return WHEEL_NAME


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    raise NotImplementedError("editable-only backend; use pip install -e .")
